version: "3.8"

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
  frontend:
    image: node:18-alpine
    volumes:
      - ./:/usr/src/fe-notes-docusaurus
    command: sh -c "cd /usr/src/fe-notes-docusaurus && npm run start"
  nodejs:
    image: node:18-alpine
    volumes:
      - ./:/usr/src/fe-notes-docusaurus
    command: sh -c "cd /usr/src/fe-notes-docusaurus && npm install -g node-gyp && npm rebuild && node_env=development npm run start:express"

volumes:
  sql_data: